# Generated by Django 4.2.17 on 2024-12-24 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Fuel price')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('CNG', 'CNG')], default='Petrol', max_length=10)),
                ('odo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Kilometers ran')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
